name: Build-Docker-Image

on: [workflow_dispatch]

jobs:
  build_docker_img:
     runs-on: ubuntu-latest
     env:
       TAG: python-api
       PAT: ${{ secrets.GITHUB_TOKEN }}
       USER: miautomation
       REGISTRY: ghcr.io
       VERSION: v1
     
     steps:
     - name: Checkout
       uses: actions/checkout@v3
       
       
     - name: Build Docker Image
       run: docker build -t $TAG .
       
     - name: Login to gHCR
       run: | 
         echo $PAT | docker login ${{ env.REGISTRY }} -u $USER --password-stdin
         docker tag $TAG ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}
         docker push ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}
         # '${{ env.REGISTRY }}/${{ env.actor }} OR ${{ env.repository_owner }}/${{ env.TAG }}:${{ env.run_id }}'
       
     - name: Image Scan
       uses: aquasecurity/trivy-action@master
       with:
          image-ref: '${{ env.REGISTRY }}/${{ env.USER }}/${{ env.TAG }}:${{ env.VERSION }}'
          security-checks: 'vuln,secret,config'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL,HIGH'
          
     - name: Upload the scan result to GitHub Security
       uses: github/codeql-action/upload-sarif@v2
       with:
          sarif_file: 'trivy-image-results.sarif'
          category: 'image'
       
